### ISSUE TITLE
Is possible to make primary a href link are working too ?

### ISSUE THREAD

**Issue by hibinojack** [jaycbrf4/wp-bootstrap-navwalker#2]
Hi,

I tried to integrated your navwalker script on my WordPress, and I working great thank you.
By the way, I do need to be able to click and access the page on primary link menu too.
but right now, it seem like a href link are able to click when they are child menu only. 

Do you have any idea how to figure out ?

**Comment by jaycbrf4** [comment]
http://stackoverflow.com/questions/19935480/bootstrap-3-how-to-make-head-of-dropdown-link-clickable-in-navbar
